name: Scheduled Requests

on:
  schedule:
    - cron: '*/1 * * * *' # 每隔 5 分钟触发一次，可根据需求自行调整

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make HTTP requests
        run: |
          curl https://qdqqd.com/
          curl https://www.qdqqd.com/
          curl https://api.qdqqd.com/
          curl https://tc.qdqqd.com/
          curl https://jqr.qdqqd.com/
    
        
          
          # 添加更多的 curl 命令来请求其他的 HTTP 接口
